version: 2.1

orbs:
  cypress: cypress-io/cypress@1

jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout

workflows:
  build_test:
    jobs:
      - build
      - cypress/run:
          start: npm start
          parallelism: 4