version: 2.1

project_directory: &project_directory ~/project

loop_save_cache: &loop_save_cache
  name: Save Loop Carthage Cache
  # key: Loop-carthage-v5-{{ .Environment.BUILD_WORKSPACE }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "Loop/Cartfile.resolved" }}
  paths:
    - LoopWorkspace/Loop/Carthage

orbs:
  cypress: cypress-io/cypress@1

jobs:
  build:
    working_directory: ~/project

    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - run: echo ls
      # - restore_cache: *loop_restore_cache
      # - run:
      #     name: update npm
      #     command: 'sudo npm install -g npm@latest'
      # - restore_cache:
      #     keys:
      #         # when lock file changes, use increasingly general patterns to restore cache
      #         - node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}
      #         - node-v1-{{ .Branch }}-
      #         - node-v1-
      # - run:
      #     name: Fetch dependencies
      #     command: npm install
      # - save_cache:
      #     paths:
      #         - node_modules  
      #     key: node-v1-{{ .Branch }}-{{ checksum "package-lock.json" }}


workflows:
  build_test:
    jobs:
      - build
      # - cypress/run:
      #     start: npm start
      #     parallelism: 4