version: 2.1

orbs:
  cypress: cypress-io/cypress@1.25.0

jobs:
  build:
    docker:
      - image: cimg/node:12.16
    steps:
      - checkout

workflows:
  build_test:
    jobs:
      - build
      # - cypress/install
      #     requires:
      #       - build
      - cypress/run:
          requires:
            - build
          record: true
          start: npm start
          parallel: true
          parallelism: 2
          group: 2 machines

        