version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          - restore_cache:
              keys:
              - cache-{{ .Branch }}-{{ checksum "package.json" }}
          start: npm start
          parallelism: 4
          - save_cache:
              key: cache-{{ .Branch }}-{{ checksum "package.json" }}
              paths:
              - ~/.npm
              - ~/.cache