version: 2.1
jobs: 
  test: 
    docker: 
      - image: cypress/base-10
    steps:
      - checkout
      - restore_cache: 
        keys: 
          - cache-{{ .Branch }}-{{ checksum "package.json" }}
    - run:
        name: Install Dependencies
        command: npm ci
    - run: npm run cy:verify
    - save_cache: 
        key: cache-{{ .Branch }}-{{ checksum "package.json" }}
        paths: 
          - -/.npm
          - -/.cache
    - run: 
        command: npm start
        background: true
    - run: npm run 

workflows:
  version: 2
    jobs:
      - test